production:
  adapter: postgresql
  encoding: unicode
  database: whatever
  pool: 5
  username: collegedesis
  password:
development:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username: 
  password:
